default_language_version:
  python: python3.7
default_stages:
  - commit
  - push
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending
      - id: fix-encoding-pragma
        args:
          - '--remove'
  - repo: 'https://gitlab.com/pycqa/flake8'
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-typing-imports==1.6.0
  - repo: 'https://github.com/pre-commit/mirrors-autopep8'
    rev: v1.5
    hooks:
      - id: autopep8
  - repo: 'https://github.com/asottile/pyupgrade'
    rev: v2.0.1
    hooks:
      - id: pyupgrade
        args:
          - '--py36-plus'
  - repo: 'https://github.com/asottile/add-trailing-comma'
    rev: v1.5.0
    hooks:
      - id: add-trailing-comma
        args:
          - '--py36-plus'
  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: v0.761
    hooks:
      - id: mypy
        args:
          - '--ignore-missing-imports'
        additional_dependencies:
          - tokenize-rt==3.2.0
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: 'https://github.com/Lucas-C/pre-commit-hooks'
    rev: v1.1.7
    hooks:
      - id: forbid-tabs
  - repo: 'https://github.com/Lucas-C/pre-commit-hooks-bandit'
    rev: v1.0.4
    hooks:
      - id: python-bandit-vulnerability-check
        args:
          - '--verbose'
          - '-c'
          - .banditrc
          - '-ll'
          - '--recursive'
          - snooker
  - repo: local
    hooks:
      - id: isort
        name: isort fix
        always_run: true
        entry: make isort
        language: system
